version: '3.1'
services:
  postgres:
    image: postgres:9.6.11
    restart: always
    ports:
    - 54320:5432
    environment:
      POSTGRES_DB: beers
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Welcome