version: '3.1'
services:
  postgres:
    image: postgres:9.6.11
    restart: always
    ports:
    - 5432:5432
    environment:
      POSTGRES_DB: beer_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Welcome
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./src/main/resources/db/migration/V1_1__Create_beer_table.sql:/docker-entrypoint-initdb.d/V1_1__Create_beer_table.sql